### ISSUE TITLE
Is this project still used?

### ISSUE THREAD

**Issue by worldofpeace** [elementary/wingpanel-indicator-a11y#11]
I'm not even seeing the .so in a elementary vm I'm using.

**Comment by alucryd** [comment]
Well it doesn't even build, so I'm guessing no.

**Comment by worldofpeace** [comment]
@cassidyjames Can you archive this one as well?

**Comment by cassidyjames** [comment]
I don't think it ever shipped, but if someone picked up the work I think we would be interested in shipping it.

**Comment by worldofpeace** [comment]
> I don't think it ever shipped, but if someone picked up the work I think we would be interested in shipping it.

Ahh I see, I think it would be a good idea if certain unshipped projects had a mention of that in their README's. (Is WIP, not ready for general use)

Very useful for downstreams, as we'd have to look into elementary's ubuntu packaging to find out,
