### ISSUE TITLE
Add a screenshot in the readme

### ISSUE THREAD

**Issue by ryonakano** [elementary/wingpanel-indicator-a11y#26]
What it says on the tin ;-)

**Comment by gsanaluiza** [comment]
Do you just want to add an image to README.md? Because you can do it with the <img> tag as in HTML and you can still style wherever you want. 
Example:
`<img width="60%" align="right" hspace="19" vspace="12" src="screenshot.png"></img>`

**Comment by cassidyjames** [comment]
@gsanaluiza no, specifically: someone needs to take a screenshot of this indicator in elementary OS and then add it to the README.

**Comment by ryonakano** [comment]
Also, we may want to add it by the markdown style: `![Alt Attribute](path/to/screenshot.png)`.

So the consequence of the README.md looks like this (this is only the top part though):

```markdown
# Wingpanel Universal Access Indicator
[![Translation status](https://l10n.elementary.io/widgets/wingpanel/-/indicator-a11y/svg-badge.svg)](https://l10n.elementary.io/engage/wingpanel/?utm_source=widget)

![Screenshot](data/screenshot.png?raw=true)

## Building and Installation
…(some lines follow)
```

**Comment by bumper314** [comment]
Note for anyone looking for an easy `Hacktoberfest`, this code isn't part of the current OS yet, you'll need to build it yourself to take the screenshot.

Ideally, follow the conventions of other wingpanel repos, such as [wingpanel-indicator-sound](https://github.com/elementary/wingpanel-indicator-sound), [wingpanel-indicator-datetime](https://github.com/elementary/wingpanel-indicator-datetime), [etc.](https://github.com/elementary?utf8=%E2%9C%93&q=wingpanel-indicator&type=&language=)

See also: https://github.com/elementary/wingpanel-indicator-keyboard/issues/53

**Comment by bumper314** [comment]
OK, I took a stab at this, but it's challenging to match the convention of the other winpanel-indicator repos.

1) You can't take screenshots on the lock screen, so I had to do this in a VM.  This also means I can't take a nice "window" screenshot with transparency, so the screenshot will have the lockscreen background.

2) The lockscreen doesn't honor the HiDPI display setting.  It also doesn't seem to honor the specified resolution, so for whatever reason, 1440x900 was the only resolution I could take a screenshot at.

So here are my results, which would we like like to use?

a) Closely matching the existing convention of a 750px wide crop:
![a11y-wingpanel](https://user-images.githubusercontent.com/43441/66709867-bfdec300-ed29-11e9-9355-d01e427925c5.png)

b) Or show the whole lock screen for context:
![screenshot](https://user-images.githubusercontent.com/43441/66709869-c66d3a80-ed29-11e9-8c7f-1f1fd4b28831.png)

**Comment by ryonakano** [comment]
@bumper314 I guess making the indicator shown in the session by setting `org.gnome.desktop.a11y always-show-universal-access-status` true allows you to take a "window" screenshot of it with transparency.

**Comment by bumper314** [comment]
@ryonakano Good call.  The wingpanel shows a lot more interesting stuff in session.  The `[-]` and `[+]` buttons aren't HiDPI though, so I'll create a bug for that.
