### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by LinArcX** [elementary/wingpanel-indicator-a11y#33]
Hi. I'm packaging this for void-linux. But they only accept release versions of software. So please release a new version.

**Comment by danirabbit** [comment]
This is intentional not released yet. Please do not package or redistribute it

**Comment by LinArcX** [comment]
Why? I mean is there any technical reason for it?

**Comment by danirabbit** [comment]
Because it's still in development and hasn't been very well tested or integrated. It's not production ready and has not shipped.
