### ISSUE TITLE
Would love to have a "Large Text" feature

### ISSUE THREAD

**Issue by feoh** [elementary/wingpanel-indicator-a11y#35]
## Prerequisites
- [ X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

As a visually disabled user I often want to be able to select some text and display it in very large type on the screen.

![Example from Alfred on OSX](https://user-images.githubusercontent.com/330070/87744289-18f7ed80-c7b9-11ea-8c19-51f11402484f.png)

**Describe the solution you'd like**

For example, I select a phone number in an email, hit the app launcher hotkey, choose the "Large Text" action and step away from the screen to actually make the phone call.

**Existing work**

Alfred on OSX has this feature, and due to the way OSX works it integrates anywhere you can select text or a text blob.

For instance, in the Contacts app, you can select a phone number, hit the Alfred hot key, and see it in very large text in the center of the screen.

Here is the description of this feature from the [Alfred Site](https://www.alfredapp.com/help/features/large-type/)
**Describe alternatives you've considered**

Having this accessible from the app launcher hot key seems like a natural fit given that the launcher already has similar features like calculation mode for numbers, but I'm not married to that. Anything that would integrate with as many apps as possible given Linux/Gnome's architectural limitations (e.g. there's no AppleEvents/Open Scripting Architecture in Gnome that I know of).

**Additional context**

**Comment by KeironO** [comment]
I think this would be a great addition, but am struggling to comprehend how best to even start implementing such a feature - given the way in which text is generated - with only a few "things" being selectable.

**Comment by feoh** [comment]
Hi I had this same thought! That's why I initially thought about making this a plugin to the launcher like the calculator one that's already present.

Way less elegant and integrated, to be sure!

**Comment by pongloongyeat** [comment]
@feoh how would this differ from say, a magnifier app? [elementary/gala](https://github.com/elementary/gala) has a picture-in-picture plugin that could be made use of with some tweaks (I think)

**Comment by feoh** [comment]
Elementary already does vastly better than your average magnifier app by providing superlative full screen zoom that works well.

I think I'm going to close this because unless you've used Alfred's Large Type feature you just can't grok what I'm getting at here.

Thanks!

**Comment by ryonakano** [comment]
Reading this issue I felt like developing a magnifier app for elementary OS. Not sure if it meets your request though because I've never used Alfred's Large Type.

The development happens at https://github.com/ryonakano/louper so if you're interested in feel free to submit issues, create PRs, etc. :smile:

I'm going to release its first release when elementary OS 6.0 is released.
